services:
  - type: web
    name: fc03-waf
    env: node
    rootDir: Backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES
        value: 8h
